/**
 * skill.json Generator
 * Generates ClawHub metadata
 * Supports both AI-powered and template-based generation
 */

import AIClient from '../ai/client.js';
import { getSkillJsonSystemPrompt, getSkillJsonUserPrompt } from '../ai/prompts.js';
import { SkillClassification } from './classifier.js';

export interface SkillJsonOptions {
  description: string;
  classification: SkillClassification;
  aiClient: AIClient;
}

export interface SkillJsonData {
  name: string;
  version: string;
  author: string;
  description: string;
  tags: string[];
  category: string;
}

/**
 * Generate skill.json content using AI
 */
export async function generateSkillJson(options: SkillJsonOptions): Promise<SkillJsonData> {
  const { description, classification, aiClient } = options;
  
  // Check if template mode
  if (aiClient.isTemplateMode()) {
    throw new Error('AI client is in template mode - use generateSkillJsonFromTemplate() instead');
  }
  
  const systemPrompt = getSkillJsonSystemPrompt();
  const userPrompt = getSkillJsonUserPrompt(description, classification.name);
  
  let content = await aiClient.completeWithSystem(systemPrompt, userPrompt);
  
  // Clean up any markdown code fences
  content = content
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/m, '')
    .replace(/```\s*$/m, '')
    .trim();
  
  const data = JSON.parse(content) as SkillJsonData;
  
  // Override name with our classified name
  data.name = classification.name;
  
  // Add detected services as tags if not present
  const serviceTags = classification.services.filter(s => !data.tags.includes(s));
  data.tags = [...data.tags, ...serviceTags];
  
  return data;
}

/**
 * Get category from skill type
 */
function getCategoryFromType(type: SkillClassification['type']): string {
  const categories: Record<string, string> = {
    monitoring: 'DevOps',
    automation: 'Productivity',
    research: 'Intelligence',
    browser: 'Automation',
    data: 'Data',
    communication: 'Communication',
    developer: 'Developer',
    utility: 'Tools',
  };
  return categories[type] || 'General';
}

/**
 * Get tags from classification
 */
function getTagsFromClassification(classification: SkillClassification): string[] {
  const tags: string[] = [classification.type];
  
  if (classification.language) {
    tags.push(classification.language);
  }
  
  // Add services as tags
  tags.push(...classification.services.slice(0, 3));
  
  // Make unique
  return [...new Set(tags)];
}

/**
 * Generate skill.json content from template (no AI required)
 */
export function generateSkillJsonFromTemplate(classification: SkillClassification, description: string): SkillJsonData {
  const tags = getTagsFromClassification(classification);
  
  return {
    name: classification.name,
    version: '1.0.0',
    author: 'Generated by SkillForge',
    description: description,
    tags,
    category: getCategoryFromType(classification.type),
  };
}

export default generateSkillJson;
